apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylb-dep
  labels:
    app: lb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lb
  template:
    metadata:
      labels:
        app: lb
    spec:
      containers:
        - name: cont1
          image: cveera95/img:v1
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: myserv-4
spec:
  selector:
    app: lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
